mylibrary/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^index/$',views.Index,name='index'),
    url(r'^index/(?P<bookuser_id>[0-9]+)$',views.Index2,name='index2'),
    url(r'^login/$',views.Login,name='login'),
    url(r'^reach_login/$',views.Reach_login,name='reach_login'),
    url(r'^reach_register/$',views.Reach_register,name='reach_register'),
    url(r'^register/$',views.Register,name='register'),
    url(r'^namesearch/$',views.Namesearch,name='namesearch'),
    url(r'^authorserach/$',views.Authorsearch,name='authorsearch'),
    url(r'^show/(?P<book_id>[0-9]+)/(?P<bookuser_id>[0-9]+)/$',views.Show,name='show'),
    url(r'^borrow/(?P<book_id>[0-9]+)/(?P<bookuser_id>[0-9]+)/$',views.Borrow_book,name='borrow_book'),
    url(r'^borrow_confirm/$',views.Borrow_confirm,name='borrow_confirm'),
    url(r'^back/(?P<book_id>[0-9]+)/(?P<bookuser_id>[0-9]+)/$',views.Back_book,name='back_book'),
    url(r'^back_confirm/$',views.Back_confirm,name='back_confirm'),
    url(r'^showhistory/(?P<bookuser_id>[0-9]+)$',views.Showhistory,name='showhistory'),
    url(r'loginout/$',views.Loginout,name='loginout'),
]

myweb/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^mylibrary/', include('mylibrary.urls',namespace='mylibrary')),
]

mylibrary/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import dateformat

# Create your models here.
class Book_list(models.Model):
	bookname = models.CharField(max_length=32,default='bookname')
	bookauthor = models.TextField(null=True)

class User(models.Model):
	user = models.CharField(max_length=20,default='user')
	password = models.TextField(max_length=20)

class Borrow_history(models.Model):
	bookname = models.CharField(max_length=32,default='bookname')
	bookauthor = models.TextField(null=True)
	time = models.DateTimeField(auto_now_add=True)
	stata = models.IntegerField(null=True)
	bookuser = models.CharField(max_length=32)

class  Back_history(models.Model):
	bookname = models.CharField(max_length=32,default='bookname')
	bookauthor = models.TextField(null=True)
	time = models.DateTimeField(auto_now_add=True)
	stata = models.IntegerField(null=True)
	bookuser = models.CharField(max_length=32)

mylibrary/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.utils import timezone
from . import models
# Create your views here.
def Index(request):
	book = models.Book_list.objects.all()
	return render(request,'mylibrary/index.html',{'book':book})

def Index2(request,bookuser_id):
	book = models.Book_list.objects.all()
	user = models.User.objects.get(pk=bookuser_id)
	return render(request,'mylibrary/index.html',{'book':book,'bookuser':user})

def Reach_login(request):
	return render(request,'mylibrary/login.html')

def Login(request):
	username = request.POST.get('user','0')
	userpassword = request.POST.get('password','0')
	user = models.User.objects.filter(user=username,password=userpassword)
	if user:
		booksuser = models.User.objects.get(user=username)
		book = models.Book_list.objects.all()
		return render(request,'mylibrary/index.html',{'bookuser':booksuser,'book':book})
	else:
		return render(request,'mylibrary/loginfailed.html')

def Reach_register(request):
	return render(request,'mylibrary/register.html')

def Register(request):
	user = request.POST.get('user','0')
	password = request.POST.get('user','0')
	create_user = models.User.objects.create(user=user,password=password)
	return render(request,'mylibrary/registersuccess.html')

def Show(request,book_id,bookuser_id):
	books = models.Book_list.objects.get(pk=book_id)
	bookuser = models.User.objects.get(pk=bookuser_id)
	return render(request,'mylibrary/show.html',{'book':books,'bookuser':bookuser})

def Namesearch(request):
	book_name = request.POST.get('bookname','0')
	userid = request.POST.get('userid','0')
	bookuser = models.User.objects.get(pk=userid)
	books = models.Book_list.objects.get(bookname=book_name)
	return render(request,'mylibrary/findresault.html',{'book':books,'bookuser':bookuser})

def Authorsearch(request):
	book_author = request.POST.get('bookauthor')
	userid = request.POST.get('userid','0')
	bookuser = models.User.objects.get(pk=userid)
	books = models.Book_list.objects.get(bookauthor=book_author)
	return render(request,'mylibrary/findresault.html',{'book':books,'bookuser':bookuser})

def Borrow_book(request,book_id,bookuser_id):
	books = models.Book_list.objects.get(pk=book_id)
	bookuser = models.User.objects.get(pk=bookuser_id)
	return render(request,'mylibrary/borrowconfirm.html',{'book':books,'bookuser':bookuser})

def Borrow_confirm(request):
	booksname = request.POST.get('bookname','0')
	booksauthor = request.POST.get('bookauthor','0')
	users = request.POST.get('user','0')
	bookuser = models.User.objects.get(pk=users)
	result = models.Borrow_history.objects.create(bookuser=bookuser.user,bookname=booksname,bookauthor=booksauthor)
	'''
	findborrow = models.Borrow_history.objects.filter(bookuser=bookuser.user,bookname=booksname,bookauthor=booksauthor)
	findback = models.Back_history.objects.filter(bookuser=bookuser.user,bookname=booksname,bookauthor=booksauthor)
	list1=[]
	for x in range(len(findborrow)):
		print type(findborrow[x])
		print findborrow[x].id
		list1.append(findborrow[x].id)
	max_id1 = max(list1)
	list2=[]
	for y in range(len(findback)):
		list2.append(findback[y].id)
	max_id2 = max(list2)
	lastborrow = models.Borrow_history.objects.get(pk=max_id1)
	lastback = models.Back_history.objects.get(pk=max_id2)
	if lastborrow.time<lastback.time:
		result = models.Borrow_history.objects.create(bookname=booksname,bookauthor=booksauthor,bookuser=bookuser.user,stata=1)
		return render(request,'mylibrary/borrowsuccess.html',{'bookuser':bookuser})
	else:
		return render(request,'mylibrary/borrowfailed.html',{'bookuser','bookuser'})
	'''
	if result:
		return render(request,'mylibrary/borrowsuccess.html',{'bookuser':bookuser})
	else:
		return render(request,'mylibrary/borrrowfailed.html',{'bookuser':bookuser})

def Back_book(request,book_id,bookuser_id):
	book = models.Book_list.objects.get(pk=book_id)
	bookuser = models.User.objects.get(pk=bookuser_id)
	return render(request,'mylibrary/backconfirm.html',{'book':book,'bookuser':bookuser})

def Back_confirm(request):
	booksname = request.POST.get('bookname','0')
	booksauthor =request.POST.get('bookauthor','0')
	users = request.POST.get('user','0')
	bookuser = models.User.objects.get(pk=users)
	result = models.Back_history.objects.create(bookuser=bookuser.user,bookname=booksname,bookauthor=booksauthor)
	'''
	findborrow = models.Borrow_history.objects.filter(bookuser=bookuser.user,bookname=booksname,bookauthor=booksauthor)
	findback = models.Back_history.objects.filter(bookuser=bookuser.user,bookname=booksname,bookauthor=booksauthor)
	list1=[]
	for x in range(len(findborrow)):
		list1.append(findborrow[x].id)
	max_id1 = max(list1)
	list2=[]
	for y in range(len(findback)):
		list2.append(findback[y].id)
	max_id2 = max(list2)
	lastborrow = models.Borrow_history.objects.get(pk=max_id1)
	lastback = models.Back_history.objects.get(pk=max_id2)
	if lastborrow.time>lastback.time:
		result = models.Back_history.objects.create(bookname=booksname,bookauthor=booksauthor,bookuser=bookuser.user,stata=1)

		return render(request,'mylibrary/backsuccess.html',{'bookuser':bookuser})
	else:
		return render(request,'mylibrary/backfailed.html',{'bookuser':bookuser})
	'''
	if result:
		return render(request,'mylibrary/backsuccess.html',{'bookuser':bookuser})
	else:
		return render(request,'mylibrary/backfailed.html',{'bookuser':bookuser})

def Showhistory(request,bookuser_id):
	history1 = models.Borrow_history.objects.all()
	history2 = models.Back_history.objects.all()
	user = models.User.objects.get(pk=bookuser_id)
	return render(request,'mylibrary/showhistory.html',{'borrowhistory':history1,'backhistory':history2,'bookuser':user})

def Loginout(request):
	return render(request,'mylibrary/index.html')

mylibrary/templates/mylibrary/backconfirm.html
<!DOCTYPE html>
<html>
<head>
	<title>还书确认</title>
</head>
<body>
{% if bookuser %}
	<label>用户名：</label>
	<a href="">{{ bookuser.user }}</a>
	<br>
	<form action="{% url 'mylibrary:back_confirm'%}" method="post">
		{% csrf_token %}
			<label>书名：
				<input type="text" name="bookname" value="{{book.bookname}}">
			</label>
			<br>
			<label>作者：
				<input type="text" name="bookauthor" value="{{book.bookauthor}}">
			</label>
			<br>
			<label>
				<input type="hidden" name="user" value="{{bookuser.id}}">
			</label>
			<input type="submit" value="确认还书">
	</form>
{% else %}
	<h1>跑去登陆</h1>
	<label><a href="{% url 'mylibrary:reach_login'%}">请登陆后借书</a></label>
	<label><a href="{% url 'mylibrary:reach_register'%}">没有账号请注册</a></label>
{% endif %}
</body>
</html>

mylibrary/templates/mylibrary/backfailed.html
<!DOCTYPE html>
<html>
<head>
	<title>还书失败</title>
</head>
<body>
{% if bookuser %}
	<label>用户名：</label>
	<a href="">{{ bookuser.user}}</a>
	<br>
	<h1>还书失败</h1><br>
	<a href="{% url 'mylibrary:index2' bookuser.id %}">重新借书</a>
{% else %}
	<h1>跑去登陆</h1>
	<label><a href="{% url 'mylibrary:reach_login'%}">请登陆后借书</a></label>
	<label><a href="{% url 'mylibrary:reach_register'%}">没有账号请注册</a></label>
{% endif %}
</body>
</html>

mylibrary/templates/mylibrary/backsuccess.html
<!DOCTYPE html>
<html>
<head>
	<title>还书成功</title>
</head>
<body>
{% if bookuser %}
	<label>用户名：</label>
	<a href="">{{ bookuser.user}}</a>
	<br>
	<h1>还书成功</h1><br>
	<a href="{% url 'mylibrary:index2' bookuser.id %}">返回书单</a>
{% else %}
	<h1>跑去登陆</h1>
	<label><a href="{% url 'mylibrary:reach_login'%}">请登陆后借书</a></label>
	<label><a href="{% url 'mylibrary:reach_register'%}">没有账号请注册</a></label>
{% endif %}
</body>
</html>

mylibrary/templates/mylibrary/borrowconfirm.html
<!DOCTYPE html>
<html>
<head>
	<title>借阅书籍</title>
</head>
<body>
{% if bookuser %}
	<label>用户名：</label>
	<a href="">{{ bookuser.user}}</a>
	<br>
	<form action="{% url 'mylibrary:borrow_confirm'%}" method="post">
		{% csrf_token %}
			<label>书名：
				<input type="text" name="bookname" value="{{book.bookname}}" />
			</label>
			<br>
			<label>作者：
				<input type="text" name="bookauthor" value="{{book.bookauthor}}" />
			</label>
			<label>
				<input type="hidden" name="user" value="{{bookuser.id}}">
			</label>
			<br>
			<input type="submit" value="借书">
	</form>
{% else %}
	<h1>跑去登陆</h1>
	<label><a href="{% url 'mylibrary:reach_login'%}">请登陆后借书</a></label>
	<label><a href="{% url 'mylibrary:reach_register'%}">没有账号请注册</a></label>
{% endif %}
</body>
</html>

mylibrary/templates/mylibrary/borrowfailed.html
<!DOCTYPE html>
<html>
<head>
	<title>借书失败</title>
</head>
<body>
{% if bookuser %}
	<label>用户名：</label>
	<a href="">{{ bookuser.user }}</a>
	<br>
	<h1>借书失败</h1><br>
	<a href="{% url 'mylibrary:index2' bookuser.id %}">重新借书</a>
{% else %}
	<h1>跑去登陆</h1>
	<label><a href="{% url 'mylibrary:reach_login'%}">请登陆后借书</a></label>
	<label><a href="{% url 'mylibrary:reach_register'%}">没有账号请注册</a></label>
{% endif %}
</body>
</html>

mylibrary/templates/mylibrary/borrowsuccess.html
<!DOCTYPE html>
<html>
<head>
	<title>借书成功</title>
</head>
<body>
{% if bookuser %}
	<label>用户名：</label>
	<a href="">{{ bookuser.user }}</a>
	<br>
	<h1>借书成功</h1><br>
	<a href="{% url 'mylibrary:index2' bookuser.id %}">返回书单</a>
{% else %}
	<h1>跑去登陆</h1>
	<label><a href="{% url 'mylibrary:reach_login'%}">请登陆后借书</a></label>
	<label><a href="{% url 'mylibrary:reach_register'%}">没有账号请注册</a></label>
{% endif %}
</body>
</html>

mylibrary/templates/mylibrary/findresault.html
<!DOCTYPE html>
<html>
<head>
	<title>搜索结果</title>
</head>
<body>
{% if bookuser %}
	<label>用户名：</label>
	<a href="">{{ bookuser.user }}</a>
	<br>
	<table>
		<tr>
			<th>书名</th>
			<th>作者</th>
			<th>借书</th>
			<th>还书</th>
		</tr>
		<tr>
			<td><a href="">{{book.bookname}}</a></td>
			<td><a href="">{{book.bookauthor}}</a></td>
			<td><a href="{% url 'mylibrary:borrow_book' book.id bookuser.id %}">借书</a></td>
			<td><a href="{% url 'mylibrary:back_book' book.id bookuser.id %}">还书</a></td>
		</tr>
	</table>
{% else %}
	<h1>请登陆</h1>
	<label><a href="{% url 'mylibrary:reach_login'%}">请登陆后借还书籍</a></label>
	<label><a href="{% url 'mylibrary:reach_register'%}">没有账号请注册</a></label>
{% endif %}
</body>
</html>

mylibrary/templates/mylibrary/index.html
<!DOCTYPE html>
<html>
<head>
	<title>主页</title>
</head>
<body>
{% if bookuser %}
	<label>用户名：</label>
	<a href="">{{ bookuser.user }}</a>
	<br>
	<table>
		<tr>
			<th>书名</th>
			<th>作者</th>
		</tr>
		{% for bo in book %}
			<tr>
				<td><a href="{% url 'mylibrary:show' bo.id bookuser.id %}">{{ bo.bookname }}</a></td>
				<td><a href="{% url 'mylibrary:show' bo.id bookuser.id %}">{{ bo.bookauthor }}</a></td>
				<td><a href="{% url 'mylibrary:borrow_book' bo.id bookuser.id %}">借书</a></td>
				<td><a href="{% url 'mylibrary:back_book' bo.id bookuser.id %}">还书</a></td>
			</tr>
		{% endfor %}
	</table>
	<form action="{% url 'mylibrary:namesearch'%}" method="post"/>
		{% csrf_token %}
			<label>按书名查找：
				<input type="text" name="bookname"/>
			</label>
			<label>
				<input type="hidden" name="userid" value="{{bookuser.id}}"/>
			</label>
			<input type="submit" value="查找"/>
	</form>
	<hr>
	<form action="{% url 'mylibrary:authorsearch'%}" method="post"/>
		{% csrf_token %}
			<label>按作者查找：
				<input type="text" name="bookauthor"/>
			</label>
			<label>
				<input type="hidden" name="userid" value="{{bookuser.id}}"/>
			</label>
			<input type="submit" value="查找"/>
	</form>
	<h6>欢迎使用</h6>
	<h6><a href="{% url 'mylibrary:showhistory' bookuser.id %}">借书记录</a></h6>
{% else %}
	<a href="{% url 'mylibrary:reach_login'%}">请登录</a><br>
	<table>
		<tr>
			<th>书名</th>
			<th>作者</th>
		</tr>
		{% for bo in book %}
			<tr>
				<td><a href="{% url 'mylibrary:show' bo.id %}">{{ bo.bookname }}</a></td>
				<td><a href="{% url 'mylibrary:show' bo.id %}">{{ bo.bookauthor }}</a></td>
			</tr>
		{% endfor %}
	</table>
	<hr>
<!--<form action="{% url 'mylibrary:namesearch'%}" method="post"/>
		{% csrf_token %}
			<label>按书名查找：
				<input type="text" name="bookname"/>
			</label>
			<input type="submit" value="查找"/>
	</form>
	<hr>
	<form action="{% url 'mylibrary:authorsearch'%}" method="post"/>
		{% csrf_token %}
			<label>按作者查找：
				<input type="text" name="bookauthor"/>
			</label>
			<input type="submit" value="查找"/>
	</form>-->
	<label><a href="{% url 'mylibrary:reach_login'%}">请登陆后借书</a></label>
	<label><a href="{% url 'mylibrary:reach_register'%}">没有账号请注册</a></label>
{% endif %}
</body>
</html>

mylibrary/templates/mylibrary/login.html
<!DOCTYPE html>
<html>
<head>
	<title>欢迎登陆</title>
</head>
<body>
<form action="{% url 'mylibrary:login'%}" method="post">
	{% csrf_token %}
		<label>用户名：
			<input type="text" name="user">
		</label>
		<br>
		<label>密码：
			<input type="password" name="password">
		</label>
		<br>
		<input type="submit" value="登陆">
</form>
<hr>
<a href="{% url 'mylibrary:reach_register'%}">注册</a>
<hr>
<label>当地时间：</label>
<textarea id="time"></textarea>
<script type="text/javascript">
	document.getElementById("time").value=new Date()
</script>
</body>
</html>

mylibrary/templates/mylibrary/loginfailed.html
<!DOCTYPE html>
<html>
<head>
	<title>登录失败</title>
</head>
<body>
<a href="{% url 'mylibrary:reach_login'%}">重新登陆</a>
</body>
</html>

mylibrary/templates/mylibrary/register.html
<!DOCTYPE html>
<html>
<head>
	<title>欢迎注册</title>
</head>
<body>
<form action="{% url 'mylibrary:register'%}" method="post">
	{% csrf_token %}
		<label>用户名：
			<input type="text" name="user">
		</label>
		<br>
		<label>密码：
			<input type="password" name="password">
		</label>
		<br>
		<input type="submit" value="注册">
</form>
<hr>
</body>
</html>

mylibrary/templates/mylibrary/registersuccess.html
<!DOCTYPE html>
<html>
<head>
	<title>注册失败</title>
</head>
<body>
<h1>恭喜你注册成功！请点击"去登陆"进行登陆</h1>
<span><a href="{% url 'mylibrary:reach_login'%}">去登陆</a></span>
</body>
</html>

mylibrary/templates/mylibrary/show.html
<!DOCTYPE html>
<html>
<head>
	<title>书单列表</title>
</head>
<body>
{% if bookuser %}
	<label>用户名：</label>
	<a href="">{{ bookuser.user }}</a>
	<br>
	<table>
		<tr>
			<th>书名</th>
			<th>作者</th>
			<th>借书</th>
			<th>还书</th>
		</tr>
		<tr>
			<td><a href="">{{book.bookname}}</a></td>
			<td><a href="">{{book.bookauthor}}</a></td>
			<td><a href="{% url 'mylibrary:borrow_book' book.id bookuser.id %}">借书</a></td>
			<td><a href="{% url 'mylibrary:back_book' book.id bookuser.id %}">还书</a></td>
		</tr>
	</table>
{% else %}
	<table>
		<tr>
			<th>书名</th>
			<th>作者</th>
			<th>借书</th>
			<th>还书</th>
		</tr>
		<tr>
			<td><a href="">{{book.bookname}}</a></td>
			<td><a href="">{{book.bookauthor}}</a></td>
		</tr>
	</table>
{% endif %}
</body>
</html>

mylibrary/templates/mylibrary/showhistory.html
<!DOCTYPE html>
<html>
<head>
	<title>借书记录</title>
</head>
<body>
{% if bookuser %}
	<label>用户名：</label>
	<a href="">{{ bookuser.user }}</a>
	<br>
	<table>
		<tr>
			<th>书名</th>
			<th>作者</th>
			<th>借书时间</th>
			<th>借书人</th>
		</tr>
		<tr>
			{% for b in borrowhistory %}
				<td>{{ b.bookname}}</td>
				<td>{{ b.bookauthor }}</td>
				<td>{{ b.time|date:"Y-m-d H:i:s" }}</td>
				<td>{{ b.bookuser }}</td>
			{% endfor %}
		</tr>
	</table>
	<hr>
	<hr>
	<table>
		<tr>
			<th>书名</th>
			<th>作者</th>
			<th>还书时间</th>
			<th>还书人</th>
		</tr>
		<tr>
			{% for a in backhistory %}
					<td>{{ a.bookname}}</td>
					<td>{{ a.bookauthor }}</td>
					<td>{{ a.time|date:"Y-m-d H:i:s" }}</td>
					<td>{{ a.bookuser }}</td>
			{% endfor%}
		</tr>
	</table>
	<a href="{% url 'mylibrary:index2' bookuser.id %}">返回书单</a>
{% else %}
	<h1>跑去登陆</h1>
	<label><a href="{% url 'mylibrary:reach_login'%}">请登陆后借书</a></label>
	<label><a href="{% url 'mylibrary:reach_register'%}">没有账号请注册</a></label>
{% endif %}
</body>
</html>